In [3]:
import numpy as np

In [4]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])

In [5]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(ar)

numpy.ndarray

In [7]:
data = [0,1,2,3,4,5,6,7,8,9]

In [8]:
answer = []
for i in data:
    answer.append(2*i)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
print(data*2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
np.array([[10,20,30,40],[50,60,70,80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [13]:
print(x.ndim)
print(x.shape)

1
(10,)


In [14]:
np.array([[x,2*x],[x,2*x]]).ndim

3

In [15]:
np.array([x,2*x]).shape

(2, 10)

In [16]:
x = np.array([1,2,3], dtype='f')

In [17]:
print(x)

[1. 2. 3.]


In [18]:
np.array([0,1,-1,0])/np.array([1,0,0,0])

C:\Users\ghckd\AppData\Local\Temp\ipykernel_5468\1727448928.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])
C:\Users\ghckd\AppData\Local\Temp\ipykernel_5468\1727448928.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [19]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
np.arange(1,10, 3)

array([1, 4, 7])

In [21]:
a[0,1] = 2
a.T

array([[0., 0., 0.],
       [2., 0., 0.],
       [0., 0., 0.]])

In [22]:
data = [0,1,2,3,4,5,6,7,8,9]
data.append(10)
data.append(11)
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [23]:
data = np.array(data)

In [24]:
data.reshape(3,4).shape

(3, 4)

In [25]:
a = data.reshape(3,-1)

In [26]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
a.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [28]:
a1 = np.ones((2,3))
a2 = np.zeros((2,3))

In [29]:
np.hstack([a1,a2])
np.vstack([a1,a2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
a1 = np.ones((3,4))
a2 = np.zeros((3,4))
np.dstack([a1,a2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [31]:
np.stack([a1, a2])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [32]:
np.stack([a1, a2], axis=2)

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [33]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [34]:
np.r_[a1, a2]

array([1, 2, 3, 4, 5, 6])

In [35]:
np.c_[a1, a2]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
x1 = np.hstack([np.zeros((3,3)), np.ones((3,2))])
x1

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [37]:
x2 = np.arange(10, 160, 10).reshape(3,-1)
x2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [38]:
np.tile(np.vstack([x1, x2]), (2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

2차원 그리드 포인트 생성

In [39]:
x = np.arange(3)
y = np.arange(5)

In [40]:
X, Y = np.meshgrid(x, y)

In [41]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [42]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [43]:
[list(zip(x,y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [44]:
x = np.arange(1,10001)
y = np.arange(10001, 20001)

In [45]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 3.73 ms


In [46]:
%%time
z = x + y

Wall time: 0 ns


In [47]:
a = np.array([1,2,3,4,5])
10 ** a

array([    10,    100,   1000,  10000, 100000], dtype=int32)

In [48]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

0,1,2,3,4,5,6

0,1,2,3,4

[0 : 3 = 0 , 1 , 2]

[1 : 4 = 1 , 2 , 3]

[2 : 5 = 2 , 3 , 4]

[3 : 6 = 3 , 4 , 5]

[4 : 7 = 4 , 5 , 6]

In [49]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])

In [50]:
y = np.arange(5)[:, np.newaxis]

In [51]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [52]:
x + np.arange(3)

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [53]:
x.mean(axis=0)

array([2., 3., 4.])

In [54]:
x.mean(axis=1)

array([1., 2., 3., 4., 5.])

In [55]:
x.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [56]:
x.min(axis=0)

array([0, 1, 2])

default가 1, 행을 의미한다.

axis = 0 이면 열을 의미한다.

In [57]:
a = np.array([[4,3,5,7],[1,12,11,9],[2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [58]:
np.sort(a, axis=1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [59]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [60]:
a.sort(axis=0)
a


array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [61]:
a = np.array([42,38,12,25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [62]:
a[j]

array([12, 25, 38, 42])

In [63]:
np.sort(a)

array([12, 25, 38, 42])

In [64]:
b = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
b

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [65]:
english_rank = np.argsort(b)[1,:]
b[:,english_rank]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [66]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [67]:
len(x)

26

In [68]:
np.mean(x)

4.8076923076923075

In [69]:
np.var(x)

115.23224852071006

In [70]:
np.var(x, ddof=1)

119.84153846153846

In [71]:
np.std(x)

10.734628476137871

In [72]:
np.max(x)

23

In [73]:
np.min(x)

-24

In [74]:
np.median(x)

5.0

In [75]:
np.percentile(x,0)

-24.0

In [76]:
np.random.seed(0)

In [77]:
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [78]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.random.shuffle(x)
x

array([5, 2, 3, 4, 1, 0, 9, 8, 7, 6])

In [80]:
a = np.array([0.5,1,2.5,3,5.5,6,8.5])

In [81]:
np.random.choice(a,5,replace=False)

array([2.5, 6. , 8.5, 3. , 5.5])

In [82]:
np.random.choice(a,3,replace=False, p=[0.1,0.3,0,0.6,0,0,0])

array([3. , 1. , 0.5])

In [83]:
np.random.randint(10,20,size=10)

array([11, 13, 13, 13, 17, 10, 11, 19, 19, 10])

동전 10번

In [84]:
np.random.choice([1,0], 10, replace=True, p=[0.5,0.5])

array([0, 1, 1, 0, 1, 0, 1, 0, 0, 0])

In [85]:
dice = np.random.randint(1, 7, size=100)
dice

array([5, 2, 3, 3, 1, 2, 2, 2, 2, 4, 4, 3, 4, 1, 4, 6, 5, 2, 3, 5, 4, 5,
       5, 5, 4, 5, 5, 5, 1, 5, 4, 3, 6, 6, 6, 1, 2, 6, 2, 4, 1, 6, 1, 2,
       3, 5, 3, 1, 6, 4, 3, 3, 6, 1, 6, 2, 1, 3, 3, 4, 3, 4, 3, 2, 3, 4,
       4, 4, 3, 4, 5, 2, 3, 4, 2, 3, 2, 5, 3, 4, 1, 4, 3, 4, 1, 1, 1, 4,
       3, 4, 1, 5, 1, 6, 1, 6, 3, 4, 3, 4])

In [86]:
np.mean(dice)

3.38

In [87]:
price = 10000
alpha = np.random.randn(250)/100
for i in alpha:
    price = price*(1 + alpha)
    print(np.round(price))


[10184. 10153.  9855. 10038.  9993. 10060. 10047. 10082. 10091.  9941.
 10094.  9975. 10097. 10021. 10110. 10094. 10061. 10000.  9901. 10187.
  9976. 10005. 10103.  9872. 10084.  9851.  9893.  9979. 10060.  9826.
 10152. 10186. 10129. 10130. 10092.  9984.  9904.  9801. 10009. 10011.
  9941. 10030. 10022. 10044.  9995. 10005.  9906. 10029. 10036. 10041.
  9806. 10144. 10019.  9958. 10174.  9964. 10134.  9918. 10008.  9871.
  9934.  9882. 10020. 10041. 10120. 10188. 10071. 10228. 10156. 10061.
  9912.  9838.  9942.  9946.  9844.  9995.  9819.  9937.  9907. 10149.
 10020.  9953. 10181.  9771. 10065.  9887.  9922. 10112. 10134.  9823.
 10042. 10109.  9962. 10063.  9945. 10052. 10011. 10026.  9909. 10086.
 10009.  9851.  9810.  9886.  9824.  9971. 10105. 10025. 10005.  9897.
 10040.  9932. 10126.  9799.  9967.  9970.  9778.  9982. 10039. 10024.
 10010.  9917. 10049. 10009.  9900.  9920. 10021. 10052.  9930. 10091.
  9933. 10013. 10043.  9999.  9965. 10082. 10052. 10120.  9962. 10069.
 10035

In [88]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [89]:
a = np.array(['a','b','b','c','a'])

In [92]:
b, c = np.unique(a, return_counts=True)
b

array(['a', 'b', 'c'], dtype='<U1')