## Data Manipulation( 데이터 조작 )

### 1. Getting Started

In [1]:
import torch

* pytorch는 새로운 tensor를 생성할 수 있는 다양한 함수들을 가지고 있다.  
* tensor는 vector, matrix, array 가 될 수 있다.

In [5]:
x = torch.arange(12) # 0:11까지 총 12개의 값을 생성
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.numel() # tensor x에 포함된 값의 수

12

In [7]:
x.shape # tensor x의 dim

torch.Size([12])

In [22]:
x.reshape(-1,1) # tensor x의 dim 변형
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
torch.zeros((3,2,1)) # 구성값이 0인 tensor 생성 (array, row, col)

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]])

In [13]:
torch.ones((3,2,1))

tensor([[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]])

In [15]:
torch.randn(2,3,4)

tensor([[[-0.1350,  2.0331, -0.3543, -0.3604],
         [ 0.6468, -0.8223, -0.1242, -3.1913],
         [ 0.3872, -0.5439,  0.5299, -0.7311]],

        [[-0.0202, -0.6419,  1.7293, -1.0337],
         [ 0.9293,  0.4020,  0.0499, -0.5199],
         [ 0.7897, -0.1098, -1.3906,  1.2760]]])

In [19]:
torch.tensor([[1,3,2], [4,2,1], [2,3,1]])

tensor([[1, 3, 2],
        [4, 2, 1],
        [2, 3, 1]])

### 2. Indexing and Slicing

In [25]:
X[-1], X[1:3]

(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [26]:
X[1,2] = 17
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5, 17,  7],
        [ 8,  9, 10, 11]])

In [27]:
X[:2,:] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

### 3. Operations

In [29]:
torch.log(x)
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [30]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y 

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [32]:
X = torch.arange(12).reshape((3,4))
Y = torch.tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
torch.cat((X,Y), dim=0) , torch.cat((X,Y), dim=1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]]),
 tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
         [ 4,  5,  6,  7,  1,  2,  3,  4],
         [ 8,  9, 10, 11,  4,  3,  2,  1]]))

In [33]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [34]:
X.sum()

tensor(66)

### 4. Broadcasting

In [35]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [40]:
b**a

tensor([[1, 1],
        [0, 1],
        [0, 1]])

### 5. Saving Memory

In [44]:
before = id(Y)
Y = Y + X
id(Y), before

(2601123176592, 2601123472944)

In [52]:
Z = torch.zeros_like(Y)
print('id(Z): ', id(Z))
Z[:] = X + Y
print('id(Z): ', id(Z))

id(Z):  2601024386608
id(Z):  2601024386608


In [53]:
before = id(X)
X += Y
id(X) == before

### 6. Conversion to Other Python Objects

In [57]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [61]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a) # item() 은 size-1의 tensor를 python scalar로 불러올 수 있다.

(tensor([3.5000]), 3.5, 3.5, 3)

### 7. Summary

### 8. Exercises

In [63]:
# 1
ex1 = torch.arange(5)
ex2 = torch.tensor([1,3,2,6,4])
ex1 == ex2, ex1 < ex2, ex1 > ex2

(tensor([False, False,  True, False,  True]),
 tensor([ True,  True, False,  True, False]),
 tensor([False, False, False, False, False]))

In [68]:
# 2
ex1 = torch.arange(3).reshape(-1,1)
ex2 = torch.tensor([[1,3],[2,6],[4,5]])
ex1 + ex2, ex1 - ex2, ex1 * ex2

(tensor([[1, 3],
         [3, 7],
         [6, 7]]),
 tensor([[-1, -3],
         [-1, -5],
         [-2, -3]]),
 tensor([[ 0,  0],
         [ 2,  6],
         [ 8, 10]]))