## Linear Algebra

In [1]:
import torch

### 1. Scalars

In [2]:
x = torch.tensor(3)
y = torch.tensor(2)

x + y, x * y, x / y, x ** y

(tensor(5), tensor(6), tensor(1.5000), tensor(9))

### 2. Vectors

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [6]:
x[2]

tensor(2)

In [7]:
len(x)

3

In [10]:
x.shape

torch.Size([3])

### 3. Matrices

In [11]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [12]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [13]:
A = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 4. Tensors

In [14]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 5. Basic Properties of Tensor Arithmetic

In [42]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()
A, B, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [43]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [44]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### 6. Reduction

In [62]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [63]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [64]:
A.shape, A.sum(axis=1).shape
A, A.sum(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([ 3., 12.]))

In [65]:
A, A.sum(axis=0)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([3., 5., 7.]))

In [66]:
A.sum(axis=[0,1]) == A.sum()

tensor(True)

In [67]:
X, X.sum(axis=0), X.sum(axis=1), X.sum(axis=2)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))

In [68]:
A.mean(), A.sum() / A.numel(), A.numel()

(tensor(2.5000), tensor(2.5000), 6)

In [69]:
A, A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([1.5000, 2.5000, 3.5000]),
 tensor([1.5000, 2.5000, 3.5000]))

### 7. Non-Reduction Sum

In [70]:
sum_A = A.sum(axis=1, keepdims=True)
A, sum_A, A.sum(axis=1), sum_A.shape

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 3.],
         [12.]]),
 tensor([ 3., 12.]),
 torch.Size([2, 1]))

In [71]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [72]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

### 8. Dot Products

Dot: $$x^T y$$

In [73]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [74]:
torch.sum(x * y)

tensor(3.)

### 9. Matirx-Vector Products

matrix(m,n) & vector(n,1)  
torch.mv == @

In [76]:
A, A.shape, x, x.shape, torch.mv(A, x), A@x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([0., 1., 2.]),
 torch.Size([3]),
 tensor([ 5., 14.]),
 tensor([ 5., 14.]))

### 10. Matrix-Matrix Multiplication

matrix(m,n) & matrix(n,k)  
torch.mm == @

In [77]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

### 11. Norms

1. $ \parallel x \parallel _p = (\sum \left\vert x \right\vert^p)^{1/p} $ : General norm

2. $ \parallel x \parallel _F = \sqrt {\sum \sum x^2} $ : Frobenius norm

In [78]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [79]:
torch.abs(u).sum()

tensor(7.)

In [80]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

### 12. Discussion