## Automatic Differentiation

In [17]:
import torch

### 1. A Simple Function

In [18]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [19]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad # The gradient is None by default

In [20]:
print(x.grad)

None


In [21]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [22]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [23]:
x.grad == 4 * x

tensor([True, True, True, True])

In [24]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [25]:
x.grad

tensor([0., 0., 0., 0.])

In [26]:
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [27]:
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 2. Backward for Non-Scalar Variables

In [28]:
x.grad.zero_()
y = x * x
y.backward(gradient=torch.ones(len(y)))
x.grad

tensor([0., 2., 4., 6.])

In [29]:
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

### 3. Detaching Computation

In [30]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

In [33]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [32]:
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [31]:
z

tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)

In [34]:
z.sum().backward()

In [36]:
x.grad == y

tensor([True, True, True, True])

In [37]:
z

tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)

In [38]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

### 4. Gradients and Python Control Flow

In [39]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [42]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [45]:
d/a

tensor(204800., grad_fn=<DivBackward0>)

In [46]:
a.grad

tensor(204800.)

In [43]:
a.grad == d / a

tensor(True)